trigger: none

pool:
  vmImage: windows-latest

variables:
- template: templates/variables.yml

jobs:
- template: templates/run-terraform.yml
  parameters:
    projectGroup: group-one
    terraformAction: plan
    terraformVersion: ${{ variables.terraformVersion }}