trigger: none

pool:
  vmImage: windows-latest

variables:
- template: templates/variables.yml

jobs:
- template: templates/run-terraform.yml
  parameters:
    projectGroup: groupone
    terraformAction: plan
    terraformVersion: ${{ variables.terraformVersion }}

- template: templates/run-terraform.yml
  parameters:
    projectGroup: grouptwo
    terraformAction: plan
    terraformVersion: ${{ variables.terraformVersion }}