trigger: none

pool:
  vmImage: windows-latest

variables:
- template: templates/variables.yml

stages:
  - stage: Group one
    jobs:
    - template: templates/run-terraform.yml
      parameters:
        projectGroup: groupone
        terraformAction: plan
        terraformVersion: ${{ variables.terraformVersion }}

  - stage: Group two
    jobs:
    - template: templates/run-terraform.yml
      parameters:
        projectGroup: grouptwo
        terraformAction: plan
        terraformVersion: ${{ variables.terraformVersion }}